spring:
  main:
    allow-circular-references: true
management:
  endpoints:
    web:
      exposure:
        include: 'health,prometheus'

# uscoreclient:
#   datasource:
#     url: 'jdbc:h2:file:./target/database/h2-uscoreclient'
#     username: sa
#     password: null
#     driverClassName: org.h2.Driver
#   # enforce_referential_integrity_on_delete: false
#   # enforce_referential_integrity_on_write: false
#   implementationguides:
#     hl_7_fhir_us_core:
#       installMode: STORE_ONLY
#       packageUrl: https://hl7.org/fhir/us/core/STU3.1.1/package.tgz
#       name: hl7.fhir.us.core
#       version: 3.1.1
#       fetchDependencies: false
#       reloadExisting: false


uscoreserver:
  datasource:
    url: 'jdbc:h2:file:./target/database/h2-uscoreserver'
    username: sa
    password: null
    driverClassName: org.h2.Driver
  # enforce_referential_integrity_on_delete: false
  # enforce_referential_integrity_on_write: false
  cors:
    allow_Credentials: true
    # These are allowed_origin patterns, see: https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/cors/CorsConfiguration.html#setAllowedOriginPatterns-java.util.List-
    allowed_origin:
      - '*'
  implementationguides:
    hl_7_fhir_us_core:
      installMode: STORE_ONLY
      packageUrl: https://hl7.org/fhir/us/core/STU3.1.1/package.tgz
      name: hl7.fhir.us.core
      version: 3.1.1
      fetchDependencies: false
      reloadExisting: false



